### ISSUE TITLE
Single click sometimes acts as double click.

### ISSUE THREAD

**Issue by jmatsushita** [iilab/openoil#2]
Consequence of #1

**Comment by antnrueh** [comment]
the single click bug seems to be gone, but now it won't open up the connections of a node, when double-clicked on (not sure if this is intended)

**Comment by jmatsushita** [comment]
Hi @antnrueh,

There is a difficult bug to identify with the double-click so I've replaced it temporarily by Cmd-Click on Mac or Windows-Click on Windows. 

Cheers,

Jun
