### ISSUE TITLE
Import Financials

### ISSUE THREAD

**Issue by jmatsushita** [iilab/openoil#34]

**Comment by antnrueh** [comment]
as far as i can see, that also applies to company details in general (except OC ID), i.e. shareholders and directors for Nigerian companies?

**Comment by antnrueh** [comment]
found some of the details, i.e. for contracts, but faced a bug: not enough space for contract details (using this query: MATCH p=(k)-[:HAS_JURISDICTION]-(a:Company)<-[hc:HAS_CONTRACTOR]-(c:Contract)<-[i:AWARDS]-(b:Company)-[:HAS_JURISDICTION]-(j) WHERE TOINT(c.value_usd) > 10000000 UNWIND nodes(p) as nodes UNWIND relationships(p) as links RETURN {nodes: [ x in collect(DISTINCT nodes) | {node: x, label: labels(x), id: id(x)}], links: collect(DISTINCT links)} as result 
 ![image](https://cloud.githubusercontent.com/assets/8330302/3922160/dc257df0-23c7-11e4-9f22-614979d657fc.png)

**Comment by jmatsushita** [comment]
Hey @antnrueh Please start an issue for each different problem. I've started a new issue for the lack of space for contract details (#35). Please start a new issue with details if your previous comment about missing company details is confirmed.

**Comment by jmatsushita** [comment]
@antnrueh What is the currency of the CSV file and is it consistent for all rows?

**Comment by antnrueh** [comment]
@jmatsushita it is GBP, in all cases and yes, it is consistent. hope that answers your question

**Comment by antnrueh** [comment]
@jmatsushita please ignore my comment about shareholders/directors. seems like i just made that up - sorry :)
