### ISSUE TITLE
"Vietnam" and "Viet Nam" - duplicate

### ISSUE THREAD

**Issue by antnrueh** [iilab/openoil#46]
Both "Vietnam" and "Viet Nam" exist in the db, although they don't in the dataset (probably a hangover from a previous version of the data)
***update: found when searched for "Viet Nam" and "Vietnam" through searchbar

**Comment by jmatsushita** [comment]
@antnrueh Latest import https://github.com/iilab/openoil/blob/master/data/BP_ownership_20140822.csv had Viet Nam.

**Comment by antnrueh** [comment]
@jmatsushita yep, the "Vietnam" / "Viet Nam" was originally a data issue, but it seems like there are two data versions online simultaniously: i.e. when you search for "Phu" (Vietnam registered Company), you will see both "Vietnam" and "Viet Nam":
![vietnam bug](https://cloud.githubusercontent.com/assets/8330302/4106122/15d75856-31b6-11e4-9043-0a7dfc0d21af.PNG)

**Comment by jmatsushita** [comment]
If the fix happened after the latest import August 22nd then it makes sense that there would inconsistencies like this. I have deleted manually the wrong country spelling node.

![image](https://cloud.githubusercontent.com/assets/356097/4107375/055d933a-31c7-11e4-99db-f9335b3a826c.png)

**Comment by antnrueh** [comment]
@jmatsushita is the screenshot from your local version? just checking because I still have the problem with two Vietnams, but don't want to reopen when you have already fixed this... thanks

**Comment by antnrueh** [comment]
the Company "Phu My 3 BOT Power" is still connected to "Viet Nam", other than in the BP spreadsheet
![phu viet nam](https://cloud.githubusercontent.com/assets/8330302/4146309/7cfc6c10-3409-11e4-9269-ba56d734499d.PNG)

**Comment by jmatsushita** [comment]
The correct spelling in the [countries.csv](https://github.com/iilab/openoil/blob/master/data/countries.csv#L243) file is Viet Nam.
