### ISSUE TITLE
Jersey query on BP Worldmap incomplete

### ISSUE THREAD

**Issue by antnrueh** [iilab/openoil#47]
When clicking on Jersey on the map, it will only show two connected company nodes ("In Saleh Gas Ltd" and "In Saleh Gas Services Ltd"), but not the ownership chain three-levels up

**Comment by jmatsushita** [comment]
It seems that it is because the top company doesn't have a jurisdiction. I will adjust the Cypher query.

![image](https://cloud.githubusercontent.com/assets/356097/4105924/0b94a8ce-31b3-11e4-8cb7-23c2dd6f122c.png)

**Comment by jmatsushita** [comment]
Works now:

![image](https://cloud.githubusercontent.com/assets/356097/4106029/c4306bb0-31b4-11e4-8915-6740e1bd9349.png)
