### ISSUE TITLE
"Request additional data" in the top bar

### ISSUE THREAD

**Issue by antnrueh** [iilab/openoil#52]
between the home sign (top left corner) and the page title: "OpenOil Data - Beta":
a link appearing as "Request additional data" which would open a separate email window directed at data.request@openoil.net

**Comment by jmatsushita** [comment]
No room there:

![image](https://cloud.githubusercontent.com/assets/356097/4106554/59abd5ac-31bb-11e4-8a98-3713025a3bc0.png)

Adding at the top right corner with an envelope Icon:

![image](https://cloud.githubusercontent.com/assets/356097/4106677/ca08b8a0-31bc-11e4-915c-dc720df36e02.png)

**Comment by antnrueh** [comment]
perfect
