### ISSUE TITLE
License text on top of downloaded spreadsheets

### ISSUE THREAD

**Issue by antnrueh** [iilab/openoil#54]
In order to avoid that the license terms get lost when people share the data (2nd hand and not directly from the website), it would be great to have three lines at the top of the downloaded csv's:
1. These data are published by OpenOil UG under the Open Database License (ODbL) v1.0: http://opendatacommons.org/licenses/odbl/1.0/
2. You are free to share, adapt and modify the data, as long as you attribute, share-alike and keep open. If you wish to use the data, or part of it, without one or more of these restrictions, please contact us for a non-share-alike licence.
3. You can find out more about OpenOil UG and the terms and conditions here: http://openoil.net/corporate-network-data-license/

**Comment by jmatsushita** [comment]
There is no standard way to add comments in CSV files. Out of the recommended ways to add meta-data to CSV files, the one I prefer is to add a license file and compress the CSV file together with the license file and make that available for download. For now this will have to be done manually. Will use .tgz format.
