### ISSUE TITLE
Saudi Arabia query on worldmap - not all ownership chains are shown

### ISSUE THREAD

**Issue by antnrueh** [iilab/openoil#56]
When clicking on Saudi Arabia on the map, you will see the two companies registered there, but only "Arabian Production..." is presented with ancestors, while "Peninsular Aviation..." is not.
![saudi arabia](https://cloud.githubusercontent.com/assets/8330302/4106215/34ad167a-31b7-11e4-954a-00b273f42971.PNG)

**Comment by jmatsushita** [comment]
![image](https://cloud.githubusercontent.com/assets/356097/4107335/8024f168-31c6-11e4-894f-13f37a140931.png)
